### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by rossman22590** [llegomark/betterreading#1]
I deployed this but it says "You have no API requests remaining today. Try again after 24 hours."  its my first time loading it :) 

any ideas?

**Comment by llegomark** [comment]
Hello Rossman22590,

As this is a paid project for one of my clients, the source code you see here is not fully complete. If you are interested in customizing it to meet your own needs, you may email me at [markllego@gmail.com](mailto:markllego@gmail.com).
